### PR TITLE
feat: background removal choice

### PR DESCRIPTION
**Pull request by kunzaatko**
- fix[bug]: Parameter names mismatch with InverseModelling
- fix[example]: moved function
- fix[spelling]: spelling in docs
- feat: Add possibility to use quantile/median for background removal

### CODE REVIEW

**Comment by RainerHeintzmann** [comment]
Can you resolve the conflict and push again? I think it is OK to merge apart from this.

**Comment by kunzaatko** [comment]
@RainerHeintzmann I think that your package is very useful! Atleast for me it was. I am working on a package [`TransferFunctions`](https://github.com/kunzaatko/TransferFunctions.jl), but it is on and off based on what functionality I need at the time. I wanted to ask you whether it would be OK for you if I adapt and refactor the code from this repo into it... I will of course cite you in the docs when I do that...

**Comment by kunzaatko** [comment]
Would that be OK with you?

**Comment by RainerHeintzmann** [comment]
Can you tell me more about the goal of the package. I assume that you are aware of the PointSpreadFunctions.jl package?
If you need the functionality of PSFDistiller.jl can you not just Import it instead? Copying code seems a bad choice for maintainability.

**Comment by RainerHeintzmann** [comment]
Thanks for the reply. Yes, sure, lets continue discussion starting second week of January.

**Comment by kunzaatko** [comment]
Hello @RainerHeintzmann, I am ready to continue the discussion now. As for the SIM that we have discussed, I have implemented the Wiener filter reconstruction and a inversion/optimization reconstruction based on `DeconvOptim`s `invert` function. I did not include it in the package that I was writing at present time, because it depends on my implementations API of the transfer function, that may be subject to change on the basis of our discussion I presume. I think it would be best to schedule a video call meeting to talk about our respective ideas and visions for the API. Does that sound good to you? What time and day would work for you?

**Pull request merged**
